#!/usr/bin/env bash

jaq -nc \
  --arg volume "$(pamixer --get-volume)" \
  --arg muted "$(pamixer --get-mute)" \
  --arg mic_muted "$( if [ "$(pactl get-source-mute 0)" = "Mute: no" ]; then echo "false"; else echo "true"; fi )" \
  '$ARGS.named'

pactl subscribe | rg --line-buffered "sink|source" | while read -r UNUSED_LINE; do
  (
    jaq -nc \
      --arg volume "$(pamixer --get-volume)" \
      --arg muted "$(pamixer --get-mute)" \
      --arg mic_muted "$( if [ "$(pactl get-source-mute 0)" = "Mute: no" ]; then echo "false"; else echo "true"; fi )" \
      '$ARGS.named'
  ); done
